const patternDefs = [
  {slug:"patterns/admin-shell.html",title:"Admin Shell",description:"Topbar, side navigation independente e content area formam o frame operacional principal.",structure:["Topbar global","Side navigation independente e colapsável","Page information area","Global feedback"],sequence:["A side navigation permanece no mesmo nível visual entre rotas.","Clicar em um item carrega a nova página de informação sem criar um novo nível de menu.","Cada grupo da navegação abre ou fecha ao clicar em seu cabeçalho.","O frame de página não recebe padding global; o Page Header ocupa a largura do workspace e possui spacing interno próprio.","O conteúdo operacional abaixo do header usa gutter space.4 (16px), salvo superfícies deliberadamente edge-to-edge."]},
  {slug:"patterns/dashboard.html",title:"Dashboard",description:"Overview operacional com métricas acionáveis, pendências e atalhos para trabalho real.",structure:["Page header","Metric row","Work queues","Activity / exceptions","Shortcuts"]},
  {slug:"patterns/admin-collection.html",title:"Collection + Filters",description:"Padrão central para imóveis, leads, clientes e usuários: header compacto, filtros progressivos, lista/tabela com scroll e paginação previsível.",structure:["Page header + icon actions","Collapsed filter trigger","Basic search/filter","Advanced filters","Data table / list","Pagination + result count"],sequence:["Page Header e área de filtros formam o bloco sticky da coleção.","Ações de alta frequência usam icon buttons de 42px: filtro neutro/ativo e criação como + primário, ambos com accessible name.","Filtros começam recolhidos; ao abrir, busca/filtro principal aparece primeiro e Filtros avançados revela os controles secundários.","O corpo da coleção usa gutter space.4 (16px) e rola abaixo do bloco sticky.","A paginação administrativa padrão usa 20 registros por página e comunica página atual, intervalo e total.","Campos simples e seguros podem ser editados inline por select/input sem retirar o usuário da coleção."]},
  {slug:"patterns/master-detail.html",title:"Master / Detail",description:"Lista persistente + detalhe para triagem rápida sem perder contexto.",structure:["Master list","Selection state","Detail panel","Context actions","History / metadata"],sequence:["O detail panel abre dentro do content workspace e não sobre a navegação global.","O header do painel permanece visível enquanto o conteúdo interno rola.","Expandir ocupa 100% do workspace de conteúdo, não o shell inteiro.","Fechar devolve o foco e o contexto à lista de origem."]},
  {slug:"patterns/crm-workspace.html",title:"CRM Workspace",description:"Workspace operacional multi-view para negociações, combinando edição inline, board drag-and-drop e detalhe contextual sem perder o funil.",structure:["Page header + icon actions","View switcher","Progressive filters","Metrics","List / board / table / calendar / gantt / activity","Workspace detail panel"],sequence:["Filtro e criação seguem o mesmo padrão compacto das demais coleções.","Lista e tabela permitem edição inline dos campos simples compatíveis com o contrato da API.","No board, arrastar um card move a negociação entre etapas.","No board web, clicar e arrastar uma área vazia faz scroll horizontal; esse gesto não intercepta cards, inputs, buttons ou editores inline.","O detail panel abre dentro do workspace e pode expandir apenas até os limites desse workspace."]},
  {slug:"patterns/crud.html",title:"CRUD",description:"Criar, ler, editar e arquivar entidades com estados, validação e destructive confirmation consistentes.",structure:["Collection","Create form","Detail","Edit","Archive/delete confirmation"]},
  {slug:"patterns/property-form.html",title:"Property Form",description:"Cadastro/edição de imóvel dividido por dados básicos, localização, preço, características, mídia e publicação.",structure:["Basic info","Address","Commercial terms","Features","Media","Publication / status"],edge:["Autosave failure","Invalid CEP/address","Price missing","No images","Duplicate property","Permission limited"]},
  {slug:"patterns/lead-management.html",title:"Lead Management",description:"Triagem, qualificação, contato, visita, proposta e fechamento com próxima ação sempre visível.",structure:["Lead context","Pipeline status","Interest / properties","Communication","Next action","History"]},
  {slug:"patterns/client-management.html",title:"Client Management",description:"Perfil, preferências, imóveis de interesse, relacionamento e histórico em um fluxo coerente.",structure:["Identity/contact","Preferences","Related properties","Appointments","Proposals","Activity"]},
  {slug:"patterns/property-search.html",title:"Public Property Search",description:"Descoberta pública com navegação por intenção, busca expandida, categorias, resultados e mapa; aqui marketplace/Airbnb é referência permitida sem substituir a identidade do produto.",public:true,contexts:["Public desktop","Public mobile","Map/list sync"],structure:["Intent rail com ícone + label","Search band","Category rail com ícone + label","Filters","Result count/sort","Property cards","Map optional","Pagination/infinite loading"],sequence:["Ícone e nome permanecem centralizados no mesmo eixo em todas as rails de descoberta.","Use gaps horizontais generosos para evitar leitura de toolbar administrativa.","No estado inicial desktop, a busca expandida ocupa uma faixa vertical própria e pode compor aproximadamente o primeiro terço da viewport junto das duas rails.","A distância vertical entre a rail superior e a busca deve ser equivalente à distância entre a busca e a rail de categorias.","Após scroll, a busca colapsa para a versão compacta sem perder finalidade, localização ou tipo selecionado.","O morph expandido → compacto usa motion produtivo de 240ms com productiveStandard: a rail superior reduz opacity e sobe levemente, a faixa de busca fecha em altura e a busca compacta entra com fade, pequeno translate e scale.","Na expansão de volta ao topo, a mesma progressão é revertida para preservar continuidade espacial.","Quando reduced motion estiver ativo, o estado muda imediatamente sem transformações intermediárias.","No Web, a rolagem vertical deve funcionar em toda a superfície visível: wheel sobre header, navegação de intenção ou busca superior precisa mover o mesmo scroller da página, sem bloquear cliques e sem criar zonas mortas de scroll."]},
  {slug:"patterns/property-detail.html",title:"Public Property Detail",description:"Galeria, preço, atributos, descrição, localização e contato orientados à decisão pública.",public:true,contexts:["Public desktop","Public mobile"],structure:["Gallery hero","Fullscreen gallery","Environment guide","Bottom thumbnails","Detail header","Features","Description","Location","Contact / CTA"],sequence:["O hero abre diretamente o fullscreen; não existe uma tela intermediária de todas as fotos.","No fullscreen, ambientes como Fachada, Sala, Cozinha, Quarto e Banheiro aparecem em uma rail superior com ícone + nome centralizados.","O ambiente ativo recebe indicação visual e o clique no item leva à primeira foto daquele grupo.","A foto principal é contida e reduzida o suficiente para permanecer entre a rail de ambientes e o dock inferior de thumbnails.","As thumbnails continuam disponíveis no rodapé para navegação foto a foto."]},
  {slug:"patterns/system-states.html",title:"Loading / Error / Empty",description:"Estados sistêmicos preservam contexto, explicam o que ocorreu e indicam próximo passo.",structure:["Context preserved","State message","Recovery action","Secondary help"],sequence:["Prefer skeleton/inline loading a full-screen blocker.","Erro explica efeito e retry quando possível.","Empty distingue first use de no results.","Success não precisa interromper o usuário."]},
  {slug:"patterns/auth-permissions.html",title:"Authentication & Permissions",description:"Login, sessão, autorização e permission denied com segurança e clareza sem vazar recursos inacessíveis.",structure:["Authentication","Session state","Role/permission gate","Denied state","Recovery/contact admin"]},
];

module.exports = { patternDefs };
