const patternDefs = [
  {slug:"patterns/admin-shell.html",title:"Admin Shell",description:"Topbar, side navigation e content area formam o frame operacional principal.",structure:["Topbar global","Side navigation","Page header","Content / routing","Global feedback"]},
  {slug:"patterns/dashboard.html",title:"Dashboard",description:"Overview operacional com métricas acionáveis, pendências e atalhos para trabalho real.",structure:["Page header","Metric row","Work queues","Activity / exceptions","Shortcuts"]},
  {slug:"patterns/admin-collection.html",title:"Collection + Filters",description:"Padrão central para imóveis, leads, clientes e usuários: search, filters, table/list, pagination e bulk actions.",structure:["Page header + create","Search/filter toolbar","Applied filters","Data table / list","Pagination + result count"]},
  {slug:"patterns/master-detail.html",title:"Master / Detail",description:"Lista persistente + detalhe para triagem rápida sem perder contexto.",structure:["Master list","Selection state","Detail panel","Context actions","History / metadata"]},
  {slug:"patterns/crud.html",title:"CRUD",description:"Criar, ler, editar e arquivar entidades com estados, validação e destructive confirmation consistentes.",structure:["Collection","Create form","Detail","Edit","Archive/delete confirmation"]},
  {slug:"patterns/property-form.html",title:"Property Form",description:"Cadastro/edição de imóvel dividido por dados básicos, localização, preço, características, mídia e publicação.",structure:["Basic info","Address","Commercial terms","Features","Media","Publication / status"],edge:["Autosave failure","Invalid CEP/address","Price missing","No images","Duplicate property","Permission limited"]},
  {slug:"patterns/lead-management.html",title:"Lead Management",description:"Triagem, qualificação, contato, visita, proposta e fechamento com próxima ação sempre visível.",structure:["Lead context","Pipeline status","Interest / properties","Communication","Next action","History"]},
  {slug:"patterns/client-management.html",title:"Client Management",description:"Perfil, preferências, imóveis de interesse, relacionamento e histórico em um fluxo coerente.",structure:["Identity/contact","Preferences","Related properties","Appointments","Proposals","Activity"]},
  {slug:"patterns/property-search.html",title:"Public Property Search",description:"Descoberta pública com search, filters, result cards e mapa; aqui marketplace/Airbnb é referência permitida.",public:true,contexts:["Public desktop","Public mobile","Map/list sync"],structure:["Search intent","Filters","Result count/sort","Property cards","Map optional","Pagination/infinite loading"]},
  {slug:"patterns/property-detail.html",title:"Public Property Detail",description:"Galeria, preço, atributos, descrição, localização e contato orientados à decisão pública.",public:true,contexts:["Public desktop","Public mobile"],structure:["Gallery","Detail header","Features","Description","Location","Contact / CTA"]},
  {slug:"patterns/system-states.html",title:"Loading / Error / Empty",description:"Estados sistêmicos preservam contexto, explicam o que ocorreu e indicam próximo passo.",structure:["Context preserved","State message","Recovery action","Secondary help"],sequence:["Prefer skeleton/inline loading a full-screen blocker.","Erro explica efeito e retry quando possível.","Empty distingue first use de no results.","Success não precisa interromper o usuário."]},
  {slug:"patterns/auth-permissions.html",title:"Authentication & Permissions",description:"Login, sessão, autorização e permission denied com segurança e clareza sem vazar recursos inacessíveis.",structure:["Authentication","Session state","Role/permission gate","Denied state","Recovery/contact admin"]},
];

module.exports = { patternDefs };
